#!/bin/bash

test_convert() {
	echo "./convert" "$*"
	./convert $@
}


test_convert c

test_convert 5

test_convert -5

test_convert +5

test_convert 3.15f

test_convert 42.42

test_convert .128f

test_convert -.256f

test_convert +.512f

test_convert 100.f

test_convert .

test_convert f

test_convert -

test_convert 0.

test_convert .6

test_convert inff

test_convert +inff

test_convert -inff

test_convert nanf

test_convert inf

test_convert +inf

test_convert -inf

test_convert nan

test_convert 1995

test_convert 2147483647

test_convert 2147483648

test_convert -2147483648

test_convert -2147483649

test_convert 9999999999999999999999999999999999999999.0

test_convert x 0.3542 64 62.0f

test_convert wel

test_convert 18f

test_convert .f

test_convert -.f

test_convert 4.24.2

test_convert 0.256f12

test_convert
